# Generated by Django 2.2.5 on 2019-09-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Andi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andiName', models.CharField(max_length=150)),
                ('andiPhotoPath', models.ImageField(upload_to='andis/')),
            ],
            options={
                'verbose_name': 'ANDi',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=100)),
                ('clientImagePath', models.ImageField(help_text='Please ensure that any client logos include the company"s name in the logo', upload_to='clientLogos/')),
            ],
            options={
                'verbose_name': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=100)),
                ('projectDescription', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Client')),
            ],
            options={
                'verbose_name': 'Project',
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnologyStacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technologyName', models.CharField(max_length=100)),
                ('technologyImagePath', models.ImageField(upload_to='tech_images/')),
                ('important', models.BooleanField(help_text='By ticking this value, the logo of the technology will appear on the home page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Project')),
            ],
            options={
                'verbose_name': 'Project Technology Stack',
                'verbose_name_plural': 'Project Technology Stacks',
                'ordering': ['-important'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Please enter a value of 0 for the cover image that will appear on the home page')),
                ('projectImagePath', models.ImageField(upload_to='site_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAndis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Project')),
                ('projectAndi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Andi')),
            ],
            options={
                'verbose_name': 'Project ANDi',
                'verbose_name_plural': 'Project ANDis',
            },
        ),
    ]
