# Generated by Django 2.2.5 on 2019-09-19 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andch_back_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectVideoPath', models.FileField(upload_to='project_videos/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Project')),
            ],
        ),
    ]
