# Generated by Django 2.2.5 on 2019-09-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andch_back_app', '0002_auto_20190916_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Andi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andiName', models.CharField(max_length=150)),
                ('andiPhotoPath', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=100)),
                ('projectDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAndis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Andi')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Project')),
            ],
        ),
    ]
