# Generated by Django 2.2.5 on 2019-09-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('andch_back_app', '0003_andi_project_projectandis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectandis',
            old_name='andi',
            new_name='projectAndi',
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectImagePath', models.CharField(max_length=250)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='andch_back_app.Project')),
            ],
        ),
    ]
